- melos.yaml
The issue was noticed in #3 - the localizations were not regenerated.
> Fix melos gen-l10n

- README.md
- packages/ubuntu_widgets/.gitignore
- packages/ubuntu_widgets/.metadata
- packages/ubuntu_widgets/LICENSE
- packages/ubuntu_widgets/README.md
- packages/ubuntu_widgets/lib/src/log_view.dart
- packages/ubuntu_widgets/lib/src/slide_show.dart
- packages/ubuntu_widgets/lib/ubuntu_widgets.dart
- packages/ubuntu_widgets/pubspec.yaml
- packages/ubuntu_widgets/test/log_view_test.dart
- packages/ubuntu_widgets/test/slide_show_test.dart
These are shared for the new [ubuntu_wsl_splash](https://github.com/ubuntu/ubuntu-wsl-splash) app.
> Import a couple of widgets from ubuntu_desktop_installer

- packages/ubuntu_widgets/lib/src/slide_show.dart
- packages/ubuntu_widgets/test/slide_show_test.dart
As discussed here: https://github.com/canonical/ubuntu-desktop-installer/pull/568#pullrequestreview-868996294
> SlideShow: add support for left/right arrow keys

- packages/ubuntu_widgets/lib/src/check_button.dart
- packages/ubuntu_widgets/lib/src/radio_button.dart
- packages/ubuntu_widgets/lib/src/toggle_button.dart
- packages/ubuntu_widgets/lib/src/toggle_button_layout.dart
- packages/ubuntu_widgets/lib/src/toggle_button_theme.dart
- packages/ubuntu_widgets/lib/ubuntu_widgets.dart
- packages/ubuntu_widgets/test/check_button_test.dart
- packages/ubuntu_widgets/test/radio_button_test.dart
- packages/ubuntu_widgets/test/toggle_button_test.dart
`CheckButton` and `RadioButton` originate from `udi/ubuntu_wizard`.
They have been generalized, and gained proper layout calculation,
accessibility, and theming support.
With overlay guidelines:
Semantics for accessibility:
> Check & radio buttons

- packages/ubuntu_widgets/lib/src/dropdown_builder.dart
- packages/ubuntu_widgets/lib/src/menu_button_builder.dart
- packages/ubuntu_widgets/lib/ubuntu_widgets.dart
- packages/ubuntu_widgets/test/dropdown_builder_test.dart
- packages/ubuntu_widgets/test/menu_button_builder_test.dart
Generic theme-agnostic builders from udi/ubuntu_wizard.
NOTE: No other changes besides minor lint fixes and the import name change.
> Import DropdownBuilder and MenuButtonBuilder

- .github/workflows/analysis.yaml
- .github/workflows/build.yaml
- .github/workflows/generate.yaml
- .github/workflows/test.yaml
- packages/ubuntu_localizations/pubspec.yaml
- packages/ubuntu_logger/pubspec.yaml
- packages/ubuntu_widgets/lib/src/log_view.dart
- packages/ubuntu_widgets/lib/src/slide_show.dart
- packages/ubuntu_widgets/pubspec.yaml
- packages/ubuntu_widgets/test/check_button_test.dart
- packages/ubuntu_widgets/test/radio_button_test.dart
https://medium.com/flutter/introducing-flutter-3-5eb69151622f
> Upgrade to Flutter 3.0

- packages/ubuntu_widgets/lib/src/rounded_container.dart
- packages/ubuntu_widgets/lib/src/rounded_list_view.dart
- packages/ubuntu_widgets/lib/ubuntu_widgets.dart
- packages/ubuntu_widgets/test/rounded_container_test.dart
- packages/ubuntu_widgets/test/rounded_list_view_test.dart
These are style-agnostic and generic enough for sharing with other apps.
> Import RoundedContainer & RoundedListView from UDI

- packages/ubuntu_widgets/lib/src/form_layout.dart
- packages/ubuntu_widgets/lib/ubuntu_widgets.dart
- packages/ubuntu_widgets/pubspec.yaml
- packages/ubuntu_widgets/test/form_layout_test.dart
> Import form layout from u-d-i

- packages/ubuntu_widgets/lib/src/slide_show.dart
- packages/ubuntu_widgets/test/slide_show_test.dart
This allows the installer to update the window title whenever the slide changes.
> SlideShow: add callback for slide changes

- README.md
- packages/ubuntu_test/.gitignore
- packages/ubuntu_test/.metadata
- packages/ubuntu_test/CHANGELOG.md
- packages/ubuntu_test/LICENSE
- packages/ubuntu_test/README.md
- packages/ubuntu_test/lib/src/file_tester.dart
- packages/ubuntu_test/lib/src/integration_tester.dart
- packages/ubuntu_test/lib/src/widget_tester.dart
- packages/ubuntu_test/lib/ubuntu_test.dart
- packages/ubuntu_test/pubspec.yaml
- packages/ubuntu_test/pubspec_overrides.yaml
- packages/ubuntu_test/test/file_test.dart
- packages/ubuntu_test/test/l10n_test.dart
- packages/ubuntu_test/test/live_pump_test.dart
- packages/ubuntu_test/test/pump_test.dart
Ref: https://github.com/canonical/ubuntu-desktop-installer/issues/1891
> Import parts of ubuntu_test from UDI

- packages/ubuntu_test/lib/src/integration_tester.dart
- packages/ubuntu_test/test/live_pump_test.dart
Imported from:
- https://github.com/canonical/ubuntu-desktop-installer/pull/2104
> feat(ubuntu_test): import IntegrationTester.runApp() from UDI

- packages/ubuntu_widgets/.gitignore
- packages/ubuntu_widgets/lib/src/animated_expanded.dart
- packages/ubuntu_widgets/lib/src/icons.dart
- packages/ubuntu_widgets/lib/src/list_widget.dart
- packages/ubuntu_widgets/lib/src/override_mouse_cursor.dart
- packages/ubuntu_widgets/lib/src/password_strength_label.dart
- packages/ubuntu_widgets/lib/src/validated_form_field.dart
- packages/ubuntu_widgets/lib/ubuntu_widgets.dart
- packages/ubuntu_widgets/pubspec.yaml
- packages/ubuntu_widgets/pubspec_overrides.yaml
- packages/ubuntu_widgets/test/animated_expanded_test.dart
- packages/ubuntu_widgets/test/list_widget_test.dart
- packages/ubuntu_widgets/test/override_mouse_cursor_test.dart
- packages/ubuntu_widgets/test/password_strength_label_test.dart
- packages/ubuntu_widgets/test/validated_form_field_test.dart
- AnimatedExpanded
- ListWidget
- OverrideMouseCursor
- PasswordStrengthLabel
- ValidatedFormField + Success/ErrorIcon
> feat(ubuntu_widgets): import non-wizard widgets from udi/ubuntu_wizard

- packages/ubuntu_widgets/CHANGELOG.md
- packages/ubuntu_widgets/pubspec.yaml
> chore: release ubuntu_widgets

- .release-please-manifest.json
- release-please-config.json
Not sure if this works as intended but worth a try...? :)
P.S. ubuntu_test cannot be released as a stable version until a stable version of flutter_html 3.0 exists
> ci(release): set up ubuntu_test

- packages/ubuntu_service/.github/workflows/ci.yaml
- packages/ubuntu_service/.gitignore
- packages/ubuntu_service/CHANGELOG.md
- packages/ubuntu_service/LICENSE
- packages/ubuntu_service/README.md
- packages/ubuntu_service/analysis_options.yaml
- packages/ubuntu_service/codecov.yaml
- packages/ubuntu_service/example/main.dart
- packages/ubuntu_service/lib/src/ubuntu_service.dart
- packages/ubuntu_service/lib/ubuntu_service.dart
- packages/ubuntu_service/pubspec.yaml
- packages/ubuntu_service/renovate.json
- packages/ubuntu_service/test/ubuntu_service_test.dart
> feat: import ufc/ubuntu_service

- packages/ubuntu_flavor/.github/workflows/ci.yaml
- packages/ubuntu_flavor/.gitignore
- packages/ubuntu_flavor/CHANGELOG.md
- packages/ubuntu_flavor/LICENSE
- packages/ubuntu_flavor/README.md
- packages/ubuntu_flavor/analysis_options.yaml
- packages/ubuntu_flavor/codecov.yaml
- packages/ubuntu_flavor/example/main.dart
- packages/ubuntu_flavor/lib/src/ubuntu_flavor.dart
- packages/ubuntu_flavor/lib/src/ubuntu_flavor_io.dart
- packages/ubuntu_flavor/lib/src/ubuntu_flavor_stub.dart
- packages/ubuntu_flavor/lib/ubuntu_flavor.dart
- packages/ubuntu_flavor/pubspec.yaml
- packages/ubuntu_flavor/renovate.json
- packages/ubuntu_flavor/test/ubuntu_flavor_test.dart
> feat: import ufc/ubuntu_flavor

- packages/platform_linux/.github/workflows/ci.yaml
- packages/platform_linux/.gitignore
- packages/platform_linux/CHANGELOG.md
- packages/platform_linux/CONTRIBUTING.md
- packages/platform_linux/LICENSE
- packages/platform_linux/README.md
- packages/platform_linux/analysis_options.yaml
- packages/platform_linux/example/desktop.dart
- packages/platform_linux/example/distro.dart
- packages/platform_linux/lib/platform.dart
- packages/platform_linux/lib/platform_linux.dart
- packages/platform_linux/lib/src/linux_desktop.dart
- packages/platform_linux/lib/src/linux_distro.dart
- packages/platform_linux/pubspec.yaml
- packages/platform_linux/renovate.json
- packages/platform_linux/test/linux_desktop_test.dart
- packages/platform_linux/test/linux_distro_test.dart
> feat: import ufc/platform_linux

- default.json
- renovate.json
> chore: import ufc/renovate-config

- .github/workflows/release-please.yaml
- .github/workflows/semantic-pr.yaml
> ci: import ufc/actions

- packages/ubuntu_logger/lib/src/ubuntu_logger.dart
This allows us to simplify Logger setup to a one-liner in all desktop provisioning-related wizard apps.
```dart
Future<void> main(List<String> args) async {
final log = Logger.setup(); // <===
return runZonedGuarded(() async {
FlutterError.onError = (error) {
log.error('Unhandled exception', error.exception, error.stack);
};
runApp(...);
}, (error, stack) => log.error('Unhandled exception', error, stack));
}
```
> feat(ubuntu_logger): promote logger setup from UDI

- packages/ubuntu_widgets/lib/src/menu_button_builder.dart
[Screencast from 2023-07-31 15-41-35.webm](https://github.com/canonical/ubuntu-flutter-plugins/assets/140617/d5c4e862-7cf8-450d-a6ef-b4b387513cc3)
```dart
MaterialApp(
theme: yaruDark,
home: Scaffold(
appBar: AppBar(),
body: Center(
child: SizedBox(
width: 200,
child: MenuButtonBuilder(
values: const ['foo', 'bar', 'baz', 'qux'],
menuPosition: PopupMenuPosition.under,
menuStyle: const MenuStyle(
minimumSize: MaterialStatePropertyAll(Size(200, 0)),
maximumSize: MaterialStatePropertyAll(Size(200, 180)),
visualDensity: VisualDensity(horizontal: 0, vertical: 0),
),
itemStyle: MenuItemButton.styleFrom(),
itemBuilder: (context, value, child) => IntrinsicWidth(
child: YaruTile(
leading: const Icon(Icons.abc),
title: Text(value.toString()),
subtitle: Text(value.toString()),
),
),
child: const …
```
> feat: allow customizing MenuButtonBuilder style & position

- .github/workflows/ci.yaml
- packages/timezone_map/test/controller_test.mocks.dart
- packages/timezone_map/test/geoip_test.mocks.dart
- packages/timezone_map/test/service_test.mocks.dart
- packages/ubuntu_test/lib/src/file_tester.dart
- packages/ubuntu_test/pubspec.yaml
- packages/ubuntu_widgets/pubspec.yaml
- packages/wizard_router/example/pubspec.yaml
- packages/wizard_router/pubspec.yaml
- packages/xdg_icons/example/pubspec.yaml
- packages/xdg_icons/pubspec.yaml
Bumps dart/flutter and yaru versions where necessary.
> chore(deps): update yaru* and flutter

- CHANGELOG.md
- packages/platform_linux/CHANGELOG.md
- packages/platform_linux/pubspec.yaml
- packages/safe_change_notifier/CHANGELOG.md
- packages/safe_change_notifier/pubspec.yaml
- packages/timezone_map/pubspec.yaml
- packages/ubuntu_flavor/CHANGELOG.md
- packages/ubuntu_flavor/pubspec.yaml
- packages/ubuntu_localizations/CHANGELOG.md
- packages/ubuntu_localizations/pubspec.yaml
- packages/ubuntu_logger/CHANGELOG.md
- packages/ubuntu_logger/pubspec.yaml
- packages/ubuntu_service/CHANGELOG.md
- packages/ubuntu_service/pubspec.yaml
- packages/ubuntu_test/CHANGELOG.md
- packages/ubuntu_test/pubspec.yaml
- packages/ubuntu_widgets/CHANGELOG.md
- packages/ubuntu_widgets/pubspec.yaml
- packages/wizard_router/CHANGELOG.md
- packages/wizard_router/example/pubspec.yaml
- packages/wizard_router/pubspec.yaml
- packages/xdg_icons/CHANGELOG.md
- packages/xdg_icons/example/pubspec.yaml
- packages/xdg_icons/pubspec.yaml
```
ubuntu_widgets         0.3.2             0.3.3             manual versioning
platform_linux         0.1.1             0.1.2             updated with minor changes
safe_change_notifier   0.3.1             0.3.2             updated with minor changes
ubuntu_flavor          0.2.1             0.2.2             updated with minor changes
ubuntu_localizations   0.3.4             0.3.5             updated with minor changes
ubuntu_logger          0.1.0             0.1.1             updated with minor changes
ubuntu_service         0.3.0             0.3.1             updated with minor changes
ubuntu_test            0.1.0-beta.7      0.1.0-beta.8      updated with minor changes
wizard_router          1.0.4             1.1.0             updated with minor changes
xdg_icons              0.0.3 …
```
> chore(release): Publish all packages

- CHANGELOG.md
- packages/wizard_router/CHANGELOG.md
- packages/wizard_router/example/pubspec.yaml
- packages/wizard_router/pubspec.yaml
> chore(release): Publish packages

- packages/ubuntu_widgets/lib/src/validated_form_field.dart
> fix: Allow `ValidatedFormField` to have a custom fill color

- CHANGELOG.md
- packages/xdg_icons/CHANGELOG.md
- packages/xdg_icons/example/pubspec.yaml
- packages/xdg_icons/pubspec.yaml
> chore(release): publish `xdg_icons` v0.0.5

- CHANGELOG.md
- packages/platform_linux/pubspec.yaml
- packages/safe_change_notifier/pubspec.yaml
- packages/timezone_map/example/pubspec.yaml
- packages/timezone_map/pubspec.yaml
- packages/ubuntu_flavor/pubspec.yaml
- packages/ubuntu_lints/CHANGELOG.md
- packages/ubuntu_lints/pubspec.yaml
- packages/ubuntu_localizations/pubspec.yaml
- packages/ubuntu_logger/pubspec.yaml
- packages/ubuntu_service/pubspec.yaml
- packages/ubuntu_test/pubspec.yaml
- packages/ubuntu_widgets/pubspec.yaml
- packages/wizard_router/example/pubspec.yaml
- packages/wizard_router/pubspec.yaml
- packages/xdg_icons/pubspec.yaml
```
Package Name   Current Version   Updated Version   Update Reason
ubuntu_lints   0.3.1             0.4.0             updated with major changes
```
> chore(release): Publish ubuntu_lints v0.4.0

- packages/ubuntu_logger/pubspec.yaml
Fixed https://github.com/canonical/ubuntu-flutter-plugins/pull/452
> chore(deps): update dependency logging to ^1.3.0
