canonical/ubuntu-flutter-plugins

- packages/ubuntu_logger/README.md
- packages/ubuntu_logger/lib/src/ubuntu_logger.dart
- packages/ubuntu_logger/lib/ubuntu_logger.dart
Add missing README, library-level docs, and make LogLevel constructor
internal to avoid that it shows up in the docs.
> logger: add missing docs

- analysis_options.yaml
As opposed to canonical/ubuntu-desktop-installer#467, these general
purpose library packages should have public API documented.
> Enable public_member_api_docs

- analysis_options.yaml
Enable `sort_pub_dependencies` to ensure that dependencies stay sorted.
Sorting dependencies makes maintenance easier, and it also plays better
together with Pubspec Assist.
> Enable `sort_pub_dependencies` linter rule

- packages/ubuntu_widgets/test/log_view_test.dart
Based on @didrocks questions in [this discussion](https://github.com/ubuntu/ubuntu-wsl-splash/pull/2#discussion_r782794192) I had to experiment and make tests to ensure the user scrolling experience with the LogView widget is not disturbed when I new line is added.
If I understood his concern correctly, the expected behavior is represented in the gif below:
It turns out that out of the box the widget already presents the desired behavior, so I just added a test to demonstrate that.
> Added test to verify user scrolling experience remains unaffected after lines are added to the LogView widget.

- packages/ubuntu_widgets/lib/src/log_view.dart
- packages/ubuntu_widgets/test/log_view_test.dart
See https://github.com/ubuntu/ubuntu-wsl-splash/pull/2/files#r782812281
> `_scrollToEnd()` schedules an asynchronous post frame callback, _but_ the `mounted` check should be inside the callback, not before scheduling the call, because the widget is not guaranteed to be mounted at that point when the callback gets called... (my bad :))
> LogView: don't attempt to scroll when unmounted

- packages/handy_window/example/lib/main.dart
- packages/handy_window/example/pubspec.yaml
Unblocks the CI:
```
handy_window_example:
Analyzing example...                                            
info • 'launch' is deprecated and shouldn't be used. Use launchUrl instead • lib/main.dart:62:22 • deprecated_member_use
1 issue found. (ran in 0.8s)
```
Same as https://github.com/canonical/ubuntu-desktop-installer/pull/804 for the installer.
> handy_window_example: fix analysis failure

- packages/ubuntu_widgets/lib/src/dropdown_builder.dart
DropdownButtonFormField gives the correct "input decorated" looks out
of the box. The reason why DropdownButton + InputDecorator was used
instead was that the FormField version was pretty badly broken i.e.
only the small text label was interactive. The issue has been fixed who
knows how long ago, so we can switch back to a simpler implementation.
Ref: canonical/ubuntu-desktop-installer#385
> DropdownBuilder: switch back to DropdownButtonFormField

- packages/timezone_map/lib/src/map.dart
- packages/timezone_map/test/map_test.dart
When formatting fractional timezone offsets, force the "en_US" locale
to ensure that "." is used as the decimal separator instead of "," that
some (e.g. nordic) locales use.
This fixes the issue that depending on the value of `Intl.defaultLocale`,
the map would try to load SVGs with wrong file names such as "tz_5,5.svg"
instead of "tz_5.5.svg" for India.
> TimezoneMap: fix fractional timezone offset formatting

- packages/ubuntu_widgets/lib/src/slide_show.dart
This gives the installer full control over slide animations so that it can perfectly match them with the window title bar. In the screencast below, it looks like the window title bar is part of the slide show but it's in fact a separate widget elsewhere in the widget tree inside a YaruWindowTitleBar. The animations just happen to match thanks to exposing the curve and duration. :)
[Screencast from 2023-01-16 17-54-50.webm](https://user-images.githubusercontent.com/140617/212730927-6cb2bb46-87f4-4ac5-8aed-b73ef8f85103.webm)
> SlideShow: expose the slide animation curve and duration

- packages/ubuntu_widgets/lib/src/dropdown_builder.dart
This allows us to move the "Device for bootloader installation" label as part of the input decoration to free up some more vertical space for the table:
> DropdownBuilder: expose input decoration to allow passing a label etc.

- .github/workflows/analysis.yaml
- .github/workflows/build.yaml
- .github/workflows/generate.yaml
- .github/workflows/test.yaml
Pin for now, we can migrate to 3.x later.
```
Found a melos.yaml file in "/home/runner/work/ubuntu-flutter-plugins/ubuntu-flutter-plugins" but no local installation of Melos.
From version 3.0.0, the melos package must be installed in a pubspec.yaml file next to the melos.yaml file.
For more information on migrating to version 3.0.0, see: https://melos.invertase.dev/guides/migrations#200-to-300
To migrate at a later time, ensure you have version 2.[9](https://github.com/canonical/ubuntu-flutter-plugins/actions/runs/4402115855/jobs/7708945053#step:5:10).0 or below installed: dart pub global activate melos 2.9.0
```
See also:
- https://github.com/canonical/ubuntu-flutter-plugins/actions/runs/4402115855/jobs/7708945053
- https://github.com/canonical/ubuntu-desktop-installer/pull/1584
> CI: pin melos at 2.90

- packages/timezone_map/lib/src/geodata.dart
- packages/timezone_map/lib/src/service.dart
- packages/timezone_map/lib/src/source.dart
- packages/timezone_map/test/controller_test.mocks.dart
- packages/timezone_map/test/service_test.dart
- packages/timezone_map/test/service_test.mocks.dart
It takes a significant amount of time to load and parse the local geodata, which is currently done lazily. While it does not prevent the timezone map from loading, it does cause a ~0.5s delay in the current location being visualized. In the desktop installer, we have plenty of time for pre-initializing such things on startup while we wait for Subiquity's initialization routines.
See also:
- canonical/ubuntu-desktop-installer#1393
> GeoService: add a way to (pre-)initialize local geodata

- packages/ubuntu_widgets/lib/src/menu_button_builder.dart
- packages/ubuntu_widgets/test/menu_button_builder_test.dart
Makes `MenuButtonBuilder` take a list of `MenuButtonEntry<T>` to allow for more control over the menu entries.
> ubuntu_widgets: Generalize MenuButtonBuilder

- .github/workflows/build.yaml
- .github/workflows/test.yaml
They were added in #44 but now those jobs keep getting stuck. I can't think of a reason why we'd need them here because `handy_window` is not here anymore. :)
> CI: drop old 18.04 jobs

- packages/ubuntu_widgets/test/key_search_test.dart
Probably was used in the original test when this was developed in the UDI repo... :)
> key_search_test.dart: clean up commented out code that accidentally slipped in

- packages/ubuntu_widgets/lib/src/menu_button_builder.dart
- packages/ubuntu_widgets/test/menu_button_builder_test.dart
Allows to override the `MenuButtonBuilder`'s `itemBuilder` with a custom widget.
[Screencast from 2023-04-17 12-32-27.webm](https://user-images.githubusercontent.com/113362648/232459774-38969636-36de-4651-89e6-98425c7e11ce.webm)
> `MenuButtonEntry`: add optional child parameter

- packages/timezone_map/test/map_test.dart
AssetManifest.bin was renamed to AssetManifest.smcbin
> test: fix timezone_map test on Flutter 3.10.1+

- packages/ubuntu_test/lib/src/common_finders.dart
- packages/ubuntu_test/lib/src/widget_tester.dart
- packages/ubuntu_test/lib/ubuntu_test.dart
- packages/ubuntu_test/test/l10n_test.dart
Calling `Localizations.of()` leaves behind dependencies on inherited widgets and eventually explodes in more complex tests.
> refactor(ubuntu_test): finder-based localizations

- melos.yaml
Handy for running for example `flutter pub upgrade` for all packages.
See also:
- https://github.com/canonical/ubuntu-desktop-installer/pull/1346
> chore(melos): add `melos pub <arg(s)>` command

- packages/ubuntu_localizations/lib/src/localizations.dart
The old name was misleading because the function doesn't do anything with `AppLocalizations` but initializes `Intl.defaultLocale`.
Moreover, there needs to be a way to pass a specific locale to make sure dates, times, and numbers are formatted according to the currently selected locale instead of the system locale.
> refactor: revise and rename setupAppLocalizations()

- packages/timezone_map/pubspec.yaml
Fixes the following warning when using timezone_map as a dependency of another package:
```
package:timezone_map has `uses-material-design: true` set but the primary pubspec
contains `uses-material-design: false`. If the application needs material icons,
then `uses-material-design` must be set to true.
```
> chore(timezone_map): remove uses-material-design

- packages/ubuntu_widgets/lib/src/menu_button_builder.dart
[Screencast from 2023-06-30 14-10-46.webm](https://github.com/canonical/ubuntu-flutter-plugins/assets/140617/737ce78a-75cd-4965-ac07-400028ee409f)
[Screencast from 2023-06-30 14-10-23.webm](https://github.com/canonical/ubuntu-flutter-plugins/assets/140617/50ed52cb-a095-4eb1-afe2-b5a2694b8959)
Fixes: canonical/ubuntu-desktop-installer#2070
> fix: adapt MenuButtonBuilder to padding & font changes in Flutter 3.10

- .release-please-manifest.json
- release-please-config.json
There are too many issues with pre-release versions:
- https://github.com/canonical/ubuntu-flutter-plugins/pull/276
- collects bogus changelog entries from older beta releases
- next version of 0.1.0-beta.5 is determined as 0.2.0-beta.5
- when the next version is forced as 0.1.0-beta.6, it sets the pubspec version to 0.1.0-beta.6+-beta.5
Keep releasing it by hand until we are able to release v0.1.0.
> revert: "ci(release): set up ubuntu_test (#275)"

- packages/ubuntu_widgets/lib/src/push_button.dart
A temporary measure to sync button, dropdown, and textfield heights.
| Before | After |
|---|---|
| ![Screenshot from 2023-08-01 09-05-59](https://github.com/canonical/ubuntu-flutter-plugins/assets/140617/19e2c65e-b564-48d7-92e3-52925b19ff3d) | ![Screenshot from 2023-08-01 09-05-41](https://github.com/canonical/ubuntu-flutter-plugins/assets/140617/ac1e4271-2b07-4e73-a98f-dd016cbe1612) |
See also:
- https://github.com/ubuntu/yaru.dart/issues/369
> fix: increase push button height to 40px

- packages/ubuntu_widgets/pubspec.yaml
yaru_icons 2 changed the API of animated icons but ubuntu_widgets do not use animated icons so either major version is fine.
> chore: relax yaru_icons version constraint

- packages/ubuntu_widgets/lib/src/menu_button_builder.dart
Uses a fixed padding for the dropdown menu entries instead of inheriting it from the button theme.
Related issue: https://github.com/ubuntu/app-center/issues/1473 (Yaru uses `EdgeInsets.all(16)` as a button padding now).
@CarlosNihelton please let me know if you think there's a better way of resolving this :)
> feat(ubuntu_widgets): use fixed padding for MenuButtonBuilder

- packages/ubuntu_service/lib/src/ubuntu_service.dart
- packages/ubuntu_service/test/ubuntu_service_test.dart
To avoid having `dynamic` for parameters.
> feat(ubuntu_service): Add generics for parameters

- packages/ubuntu_widgets/lib/src/menu_button_builder.dart
In this PR:
- The MenuButtonBuilder shouldn't take the full width and should scale depending on the children that it possesses
fix ubuntu/app-center#1530
> fix: The MenuButtonBuilder should scale depending on his childrens

- packages/ubuntu_widgets/lib/src/animated_expanded.dart
Since the `BoxConstraints` already manages the animated size, I think it is better that the user handles the flex value of the widget and we keep it without flex as default. This makes it easier to use it code with unconstrained size, like in a scrollable context for example.
Another minor refactor is also included here which moves from `Container` to `ConstrainedBox`.
> fix: Remove Flexible from AnimatedExpanded

- packages/wizard_router/lib/src/controller.dart
- packages/wizard_router/lib/src/scope.dart
- packages/wizard_router/test/wizard_router_test.dart
* Adds an optional `errorRoute` to `WizardController`
* Catches exceptions in `_loadRoute` and returns `errorRoute` instead, if provided
* Adds a `showError()` method that jumps to the `errorRoute`, if provided
> feat(wizard_router): add errorRoute and showError()

- packages/ubuntu_flavor/lib/src/ubuntu_flavor.dart
- packages/ubuntu_flavor/lib/src/ubuntu_flavor_io.dart
- packages/ubuntu_flavor/lib/src/ubuntu_flavor_stub.dart
- packages/ubuntu_flavor/test/ubuntu_flavor_test.dart
This simplifies the `ubuntu_flavor` package but introduces a few breaking changes:
* `id` has been replaced by the enum's `name` getter and most of those have changed
* the `name` property has been renamed to `displayName`
* `detect()` returns `UbuntuFlavor.unknown` instead of `null` if flavor can't be detected
> feat(ubuntu_flavor)!: use enum instead of immutable class

- packages/xdg_icons/lib/src/icon.dart
Reopening of https://github.com/canonical/ubuntu-flutter-plugins/pull/385 with signed commits
- If an icon fails to resolve, the caller can provide an option render function to use in its place
We might want to show some sort of nice "Icon not found" icon when it is unavailable on a system for any reason.
```dart
return XdgIcon(
name: iconName,
size: size,
iconNotFoundBuilder: () {
return SizedBox(
width: size.toDouble(),
height: size.toDouble(),
child: Center(
child: Text(
iconName.isEmpty ? "U" : iconName[0].toUpperCase(),
style: Theme.of(context).textTheme.displayLarge)));
});
```
> feat: providing an optional render when an icon fails to resolve entirely

- packages/ubuntu_widgets/lib/src/key_search.dart
- packages/ubuntu_widgets/lib/src/list_widget.dart
Since we need to be able to tab out of the list in ubuntu bootstrap this PR makes it possible to pass in a focus node that is activated when the user presses tab.
> feat: Possibility to tab out of ListWidget

- packages/wizard_router/lib/src/controller.dart
- packages/wizard_router/lib/src/scope.dart
- packages/wizard_router/test/wizard_router_test.dart
add a previous function ro resolve #432
> feat: wizard_router add previous

- .github/workflows/ci.yaml
Since ubuntu_test depends on a pre-release of flutter_html it shouldn't have been published as a non-prerelease package (to pass all the pub checks), let's ignore it from that check until the stable version of flutter_html is released.
> ci: Don't dry-run publish ubuntu_test

- CHANGELOG.md
- packages/ubuntu_test/CHANGELOG.md
- packages/ubuntu_test/pubspec.yaml
- packages/wizard_router/CHANGELOG.md
- packages/wizard_router/example/pubspec.yaml
- packages/wizard_router/pubspec.yaml
```
Package Name    Current Version   Updated Version   Update Reason
ubuntu_test     0.2.0             0.2.1             manual versioning
wizard_router   1.3.0             1.4.0             updated with minor changes
```
> chore(release): publish packages

- .github/workflows/release-prepare.yml
- .github/workflows/release-publish.yml
- .github/workflows/release-tag.yml
This adds `fetch-depth: 0` so that all tags are fetched and adds the action permission to the tag job so that it can start the publishing job.
> ci: Add fetching of tags and needed permissions for publishing

- packages/ubuntu_widgets/lib/src/menu_button_builder.dart
In some cases you'll get the following without this fix applied:
```
This widget has been unmounted, so the State no longer has a context (and should be considered defunct). 
```
> fix: MenuButtonBuilder only find render object when mounted

- packages/ubuntu_localizations/lib/src/localizations.dart
If `Intl.defaultLocale` is initialized with `und` (undefined) or `POSIX` localizing a `DateTime` with `DateFormat` (and possibly other things) will throw an exception. See https://github.com/ubuntu/app-center/issues/1659 for more details.
A simple workaround has been suggested [here](https://github.com/ubuntu/app-center/issues/1884#issuecomment-2605281302).
> fix(ubuntu_localizations): use fallback if locale is 'POSIX' or 'und'

- melos.yaml
- packages/safe_change_notifier/pubspec.yaml
- packages/timezone_map/pubspec.yaml
- packages/ubuntu_localizations/pubspec.yaml
- packages/ubuntu_test/pubspec.yaml
- packages/ubuntu_widgets/pubspec.yaml
- packages/wizard_router/example/pubspec.yaml
- packages/wizard_router/pubspec.yaml
- packages/xdg_icons/example/pubspec.yaml
- packages/xdg_icons/pubspec.yaml
Due to the changes in #462 `ubuntu_localizations` requires at least Flutter 3.27.
Turns out we're tracking the Flutter version constraints for all packages in the `melos.yaml` (i.e. running `melos bootstrap` updates the Flutter version constraints in all packages). This means we need to bump it for all packages.
UDENG-6671
UDENG-6586
> chore(ubuntu_localizations): bump minimum Flutter version

- .github/workflows/pr.yaml
Updates the CLA workflow to the [latest version](https://github.com/canonical/has-signed-canonical-cla). The `exempted-bots` has been removed, as proper github bots (with usernames ending in `[bot]` are automatically excluded from the check. We need to continue explicitly excluding weblate, since their automation is using a normal github account. Also see https://github.com/canonical/has-signed-canonical-cla/pull/77
> ci: update CLA check to v2

- packages/ubuntu_localizations/CHANGELOG.md
- packages/ubuntu_localizations/pubspec.yaml
- packages/ubuntu_test/CHANGELOG.md
- packages/ubuntu_test/pubspec.yaml
- packages/ubuntu_widgets/CHANGELOG.md
- packages/ubuntu_widgets/pubspec.yaml
Releases new versions of the following packages:
- `ubuntu_localizations` `0.5.2` (migrated to Flutter `>=3.27` with minor changes)
- `ubuntu_test` `0.2.3` (updated `yaru_test` to `^0.3.0`)
- `ubuntu_widgets` `0.7.2` (updated `yaru` to `>=6.0.0 <8.0.0`)
(I'll manually release those after merging the PR and will have a look at the automated release workflows later)
UDENG-6586
> chore: release packages

- packages/xdg_icons/lib/src/icon.dart
- packages/xdg_icons/pubspec.yaml
This allows using SVG icons that have for example the <style> attribute set. An example of an icon theme using this is KDE's Breeze. flutter_svg doesn't support this and without it Breeze's dark icons would render as black even though they're supposed to be white.
See https://github.com/dnfield/flutter_svg/issues/105 for context.
Fixes #472.
CC @jpnurmi
> feat(xdg_icons): replace flutter_svg dependency with jovial_svg

- packages/xdg_icons/CHANGELOG.md
- packages/xdg_icons/pubspec.yaml
Release `xdg_icons` `0.1.1` including the changes from #475.
> chore: publish xdg_icons 0.1.1
